# Generated by Django 3.1.2 on 2020-11-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('Hello', 'Just to say hi'), ('Biz', 'Business'), ('my_work', 'Blog'), ('sm', 'Social Media'), ('lol', 'Hate mail'), ('none', 'Other')], default='Just to say hi', max_length=50),
        ),
    ]
