# Generated by Django 3.1.2 on 2020-11-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('greeting', 'Just saying Hi!'), ('work', 'Business'), ('ideas', 'Ideas'), ('hm', 'Hate mail'), ('bored', 'Other')], default='Just saying Hi!', max_length=50),
        ),
    ]
